### ISSUE TITLE
SDP problem eats RAM very fast.

### ISSUE THREAD

**Issue by ghost** [gsagnol/picos#71] opened 2018-07-04 14:43 UTC
I am running a semidefinite program with 64x64 matrices and get "out of memory errors" every time. My solver is mosek.

**Comment by mjstahlberg** [comment] 2018-07-04 19:43
Hello @qubix12, could you try with the version found in the master branch of https://github.com/Viech/picos? (Copying the `picos` folder found in the ZIP download in the same directory as your scripts should work.) This fork has a re-implementation of the interface to MOSEK and will eventually go upstream. If that doesn't help, then the issue may be with our matrix expressions and we would need some exmaple to reproduce your problem.

**Comment by ghost** [comment] 2018-07-04 19:55
@Viech Thank you for the suggestion, as will try it out as soon as I can. Just to elaborate a bit more, I am running my code on a paperspace cloud server with 60 GB RAM, so running out of RAM looks really awkward. I also created an extra 100 GB swap file, still the same problem. I will let you know what this branch gives.

**Comment by gsagnol** [comment] 2018-07-05 07:27
With 64x64 matrices,  RAM should NOT be an issue ! Could you please send us a small example, so we understand what is going wrong?

**Comment by ghost** [comment] 2018-07-05 07:54
I will, as soon as I make it run again. Has the partial transpose function changed? In order to take partial transposes of all 2x2 submatrices of a 64x64 matrix, I used to do: 

` pic.partial_transpose(Q1,(2,2))`

and now it gives: 

`AssertionError: the size of subsystems do not match the size of the entire matrix`

I did not change the code.

To make it clear, this example fails: 

```
import picos as pic
import cvxopt as cvx
P = pic.Problem()
X = P.add_variable('X',(8,8))
X.value = cvx.matrix(range(64),(8,8))

# taking the partial transpose with respect to all 2x2 subsystems
print(pic.partial_transpose(X,(2,2))) 
```

**Comment by mjstahlberg** [comment] 2018-07-09 01:13
I can confirm that this is broken on master, and it was broken already before I started working on PICOS (tested with c934d03). I also haven't fixed it by accident, it doesn't work on my working branch either.

**Comment by ghost** [comment] 2018-07-10 08:20
Any news on why this happens? I am trying to compare the partial_transpose function from the current master branch to older ones, I don't see what changed.

**Comment by mjstahlberg** [comment] 2018-07-10 14:05
I bisected with your example and found that c322beb is the culprit, its parent 7de8581 prints
```
[ 0.00e+00  1.00e+00  1.60e+01  1.70e+01  3.20e+01  3.30e+01  4.80e+01 ... ]
[ 8.00e+00  9.00e+00  2.40e+01  2.50e+01  4.00e+01  4.10e+01  5.60e+01 ... ]
[ 2.00e+00  3.00e+00  1.80e+01  1.90e+01  3.40e+01  3.50e+01  5.00e+01 ... ]
[ 1.00e+01  1.10e+01  2.60e+01  2.70e+01  4.20e+01  4.30e+01  5.80e+01 ... ]
[ 4.00e+00  5.00e+00  2.00e+01  2.10e+01  3.60e+01  3.70e+01  5.20e+01 ... ]
[ 1.20e+01  1.30e+01  2.80e+01  2.90e+01  4.40e+01  4.50e+01  6.00e+01 ... ]
[ 6.00e+00  7.00e+00  2.20e+01  2.30e+01  3.80e+01  3.90e+01  5.40e+01 ... ]
[ 1.40e+01  1.50e+01  3.00e+01  3.10e+01  4.60e+01  4.70e+01  6.20e+01 ... ]
```
@gsagnol do you see your error at a glance? I can dig into this but it might take me longer since I first have to figure out how your code is supposed to work.

**Comment by gsagnol** [comment] 2018-07-11 06:47
I will try to give it a look tomorrow.

**Comment by ghost** [comment] 2018-07-11 14:42
@Viech , Thanks, reverting to that checkpoint made my code work again. I was thinking about this memory leak issue. I am running 2 SDPs inside a loop, one feeding the other. On the mosek website, they say: 

> Make sure to delete task and environment when not in use anymore
>     Using the with-construction (available in python 2.6 and later) will allow automatic deletion of the environment and task. If this is not an option, use Env.del() and Task.del() to destroy the objects. Failing to do this may cause memory leaks in some cases.

Is this equivalent to calling 

`P. reset_mosek_instance(onlyvar=True)`
immediately after `P.solve() `? I am trying it now and will let you know if this is the reason.

**Comment by gsagnol** [comment] 2018-07-11 16:13
Hi,
OK, I checked and now I remember. Due to the request of another user, the syntax of partial_transpose has been updated, so we lost backward compatibility! If you read the doc, you should understand that to take the partial transpose of every 2x2 submatrix of a 64x64 matrix, you now have to make:
`pic.partial_transpose(X,(32,2))`.

The old input of the function was referring to the size of the first subsystem, assuming the matrix was a tensor product of two matrices. The new format does not assume that there are only 2 subsystems, so you have to give the size of each subsystem. In your case, taking the transpose of (2,2) blocks is the same as taking the transposition of the second subsystem, where the first subsystem is of size 32 and the second is of size 2.

**Comment by mjstahlberg** [comment] 2018-07-11 17:55
@gsagnol please reopen; the original issue was not about `partial_transpose`. :wink:

**Comment by ghost** [comment] 2018-07-11 19:46
@Viech @gsagnol I second the above, we "solved the partial_transpose" issue by reverting to an older commit. The problem with memory leakage is the actual issue though. 
This is what I tried in the meantime: 


1) I added a line after` P.solve(...)` like so: 
```
P.solve(.....)
P. reset_mosek_instance(onlyvar=True)
```
with no effect.

2) I added two other lines after `P.solve()`
```
P.solve(...)
P.msk_task.__del__()
P.msk_env.__del__()
```
and it tells me `"None type object has no attribute __del__()". `

Still working on it.

**Comment by mjstahlberg** [comment] 2018-07-11 22:34
Are you having an issue when solving a lot of problem modifications sequentially? When solving the same (modified) problem instance over and over again with the same solver, the solver's problem instance is either updated (if supported by the solver and its implementation) or reset. Looking at my MOSEK implementation it might indeed be the case that the reset (which should occur only if variables or constraints are *deleted* from the instance) leaks memory, given that I did
```
if self.int is not None:
    self.int.dispose()
```
inside `MOSEKSolver.__del__` but only
```
self.int = None
```
inside `MOSEKSolver.reset_problem`, where `self.int` is MOSEK's problem representation.

I have fixed that on my branch so that `dispose` is called on a reset, too. You can find the [latest version of that branch](https://gitlab.com/picos-api/picos/tree/future) (now called `future`) on GitLab now.

If that doesn't help it would be nice if you could give me a complete example so that I can hook a memory profiler to it.

**Comment by ghost** [comment] 2018-07-12 10:16
@Viech 

Ok, so my code is something like this:
```
val1, val2 = np.zeros(64,64)
for iteration in range(10): 
    val1 = myFirstSolver(args, val2)
    val2 = mySecondSolver(args, val1)
```
where `myFirstSolver` and `mySecondSolver` are two functions performing SDP with picos and mosek. I can't post the whole code here since it is related to a paper that has not yet been published. 
So if I switch to your branch, do I need to add anything after `P.solve(...)` ?

**Comment by mjstahlberg** [comment] 2018-07-12 12:34
@qubix12, if you clone `git@gitlab.com:picos-api/picos.git` and checkout the `future` branch than this will already contain my fix attempt.

You shouldn't need to perform any cleanup after `solve`, that's PICOS' responsibility.

From your example I can't determine whether the previos version of my branch (without the fix) would run into the questionable code section. This would depend on whether variables or constraints are removed or replaced in the two PICOS problem instances. If you are just adding variables and constraints, then the MOSEK problem instances should get updated iteratively and my patch should have no effect.

**Comment by ghost** [comment] 2018-07-13 18:27
@Viech I tried your branch. Same issue unfortunately.

**Comment by mjstahlberg** [comment] 2018-07-13 23:41
Well that's unfortunate. :disappointed:  Can you be more precise what your `my*Solver` functions do with `val1` and `val2`? I don't need to know how the matrices are assembled/modified, but there's not much more I can do without some kind of example that allows me to reproduce your problem.

**Comment by mjstahlberg** [comment] 2018-07-15 18:39
Another option would be if you try to hook a memory profiler to your application, and post the output. That's in a nutshell what I would do.

**Comment by gsagnol** [comment] 2018-07-16 14:13
Hi @qubix12 ,

We are moving the project to GL. I created a duplicate of your question there, please use the following page for further communications about this issue:
https://gitlab.com/picos-api/picos/issues/73

At this point, we really need an example to understand why there is a memory problem. Si I woud invite you to send us a small example per email if you do not want your code to be published.

**Closed as completed by gsagnol** 2018-07-16 14:13 UTC
