### ISSUE TITLE
Hermitian matrices optimization with PSD constraint

### ISSUE THREAD

**Issue by RPinto89** [gsagnol/picos#67] opened 2018-03-14 11:37 UTC
Hi, 
I'm using PICOS as interface to formulate a specific optimization problem.
![image](https://user-images.githubusercontent.com/14095892/37399260-1f789188-2779-11e8-91a3-eed312833fa2.png)
Basically I have as variables 3 matrices, "S", "v", and "l", which I need them to be complex (S) and hermitian (v and l). My only contraint is that the matrix formed by the variables as in the figure above must be PSD (positive semi-definite).
I formulated all this as:

```
prob = pic.Problem()
        S = prob.add_variable('S', (buses[b].num_phase, buses[b].num_phase), 'complex')
        l = prob.add_variable('l', (buses[b].num_phase, buses[b].num_phase), 'hermitian')
        v = prob.add_variable('v', (buses[b].num_phase, buses[b].num_phase), 'hermitian')
        
        # making constraint thar makes this matrix to be PSD
        prob.add_constraint(((v & S) // (S.H & l)) >> 0)
```
Now, my question relates on how to formulate the objective function. H_i in the figure above is basically the sum of all the elements:
![image](https://user-images.githubusercontent.com/14095892/37399735-80882c12-277a-11e8-83a6-b91eae70de1b.png)
where the elements the "(y)" are complex target matrices which are also hermitian. I did:
`prob.set_objective('min', 
 (2*n_chi + 3) * ((S - S_i_ref) | (S - S_i_ref)) + ((S - S_Ai_ref) | (S - S_Ai_ref)) +
(n_chi + 1) * ((l - l_i_ref) | (l - l_i_ref)) + ((l - l_Ai_ref) | (l - l_Ai_ref)) +
2 * ((v - v_i_ref) | (v - v_i_ref))`
When I try to solve() I get an error:

> if not(self.objective[1] is None) and not(self.objective[1].is_real()):
> AttributeError: 'QuadExp' object has no attribute 'is_real'

Does anyone have an idea on how to formulate the objective function?
To clarify: all the objective function elements 
![image](https://user-images.githubusercontent.com/14095892/37400520-178173b0-277d-11e8-98c3-ab60ea16a783.png)
 respect to the square of the Frobenius norm:
![image](https://user-images.githubusercontent.com/14095892/37400179-f7d5008c-277b-11e8-9435-820cd97e9b6d.png)

**Comment by RPinto89** [comment] 2018-03-14 14:51
Can I use something like what was suggested in: https://github.com/gsagnol/picos/issues/16
and add auxiliary variables for each of the Frobenius norms and also adding a constraint:
```
t1 = P.add_variable('t1',1)
t2 = P.add_variable('t2',1)
t3 = P.add_variable('t3',1)
P.add_constraint(abs(S - S_i_ref)**2 < t1)
P.add_constraint(abs(v - v_i_ref)**2 < t2)
P.add_constraint(abs(l - l_i_ref)**2 < t3)
P.add_constraint(t1+t2+t3 < 0.1)

P.set_objective('min',t1 + t2 + t3)
P.solve() )
```
Will this be equivalent to the sum of the original Frobenius norms?

**Comment by mjstahlberg** [comment] 2018-03-14 18:56
Assuming that PICOS does not yet support complex numbers in quadratic objectives, such an epigraph reformulation with auxiliary variables should indeed be the correct way to work around it.

A constraint like `t1+t2+t3 < 0.1` shouldn't be needed as you are already minimizing the same sum, except when you really want a point with a poor objective function value to be considered infeasible.

**Comment by RPinto89** [comment] 2018-03-15 11:04
Thank you for the help.
A question still remains: does the
`abs(S - S_i_ref)**2` 
compute the Frobenius norm, or should I do instead something like
`(S - S_i_ref | S - S_i_ref) < t1` ?

Thank you

**Comment by RPinto89** [comment] 2018-03-15 11:51
Well, trying to do something like
`(S - S_i_ref | S - S_i_ref) < t1`
gives me an error when trying to solve the problem:

> AttributeError: 'QuadExp' object has no attribute 'is_real'

**Comment by mjstahlberg** [comment] 2018-03-15 19:18
I can't tell for sure as my knowledge of complex algebra and its notational conventions is rusty, but I would also assume that `abs(S - S_i_ref)**2` and `(S - S_i_ref | S - S_i_ref)` should give the same result but different implementations have it that the latter fails and raises an `AttributeError`.

**Comment by gsagnol** [comment] 2018-03-16 08:12
This looks like a bug, `abs(z)**2` should return `(z|z)`, where the scalar product of complex variables is to be understood as `z.conj.T * z`.
Here a minimal example:
```
P = picos.Problem()
z=P.add_variable('z',2,'complex')
z.value = cvx.matrix([1+2j,3-1j])
print np.linalg.norm([1+2j,3-1j])**2  # correct value is 15
print abs(z)**2                                 # returns wrong value
print z|z                                           # correct 
print z.conj.T * z                              # correct
```

**Comment by RPinto89** [comment] 2018-03-16 11:16
Hi, 
@gsagnol are you saying that I shouldn't use the `abs(S - S_i_ref)**2`, and instead use `(S - S_i_ref | S - S_i_ref)`. My problem with  `(S - S_i_ref | S - S_i_ref)` is that when I go and solve the problem, I get the following error, as said before:

> AttributeError: 'QuadExp' object has no attribute 'is_real'

When I try to follow your previous example, but for matrix dimensions like the ones I'm using in my problem formulation, I get:

`S.value = cvx.matrix([[1+2j,3-1j, 1+2j], [3-1j, 1+2j,3-1j], [3-1j, 1+2j,3-1j]])`
`print(S)`
> [ 1.00e+00+j2.00e+00  3.00e+00-j1.00e+00  3.00e+00-j1.00e+00]
> [ 3.00e+00-j1.00e+00  1.00e+00+j2.00e+00  1.00e+00+j2.00e+00]
> [ 1.00e+00+j2.00e+00  3.00e+00-j1.00e+00  3.00e+00-j1.00e+00]

`print(abs(S)**2)`
> #quadratic expression: ||S||**2 #

`print(S|S)`
> (70+0j)

`print(S.conj.T * S)`
> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.2\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
>     exec(exp, global_vars, local_vars)

Now, in my problem formulation I have (S - S_i_ref), not just S. Defining:
```
print(S_i_ref)
[-4.10e-03-j0.00e+00 -1.16e-03-j1.81e-03 -7.85e-03+j1.91e-03]
[-3.34e-03+j2.38e-03 -2.00e-03-j8.00e-04 -5.28e-03+j6.11e-03]
[-3.34e-03-j2.38e-03  1.05e-04-j2.15e-03 -7.50e-03-j3.00e-03]
```
I get the following similar results:
`print(abs(S - S_i_ref) ** 2)`

> #quadratic expression: ||S -S_i_ref||**2 #

`print((S - S_i_ref)|(S - S_i_ref))`

> (70.13109322131245+0j)

`print((S - S_i_ref).conj.T * (S - S_i_ref))`

> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.2\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
>     exec(exp, global_vars, local_vars)
>   File "<input>", line 1, in <module>
>   File "C:\Users\rbpinto\Anaconda3\envs\opf_dist\lib\site-packages\picos\expression.py", line 1014, in __mul__
>     raise Exception('not implemented')
> Exception: not implemented

How do you suggest that I formulate the Forbenius norm of (S - S_i_ref),  (and the other variables as well), inside a minimization objective function?

Thank you!

**Comment by RPinto89** [comment] 2018-03-19 14:22
Any thoughts?
Thanks!

**Comment by mjstahlberg** [comment] 2018-03-19 17:05
Summing up, it appears that `abs(z)**2` is broken for complex numbers `z` as @gsagnol pointed out, while `z.conj.T * z` "works" (in the sense that it computes a dot product) only for vectors and vectorized matrices. In fact, the `not implemented` exception is to be understood as "PICOS does not support multiplying matrices of affine expressions, which includes matrices of variables, at all", from what I read in the code.

@RPinto89, are you having any trouble when you write `(S - S_i_ref)|(S - S_i_ref)`? If not, then this should be the way to go until we get to fix `abs(S - S_i_ref)**2`.

**Comment by RPinto89** [comment] 2018-03-19 17:09
Hi, 

My problem with `(S - S_i_ref | S - S_i_ref)` is that when I go and solve the problem, I get the following error, as said before:

> AttributeError: 'QuadExp' object has no attribute 'is_real'

**Comment by mjstahlberg** [comment] 2018-03-19 17:39
Sorry, I overlooked that.

The error seems to be triggered in `problem.py` when a non-linear constraint is handled in the `to_real` function:
```
                if c.Exp1.is_real():
                    E1 = _copy_exp_to_new_vars(c.Exp1, cvars, complex=False)
                else:
                    E1 = _copy_exp_to_new_vars(c.Exp1, cvars, complex=True)
```
For quadratic expressions, `Exp1` is a `QuadExp` which does not have the `is_real` method as only `AffinExp` have it.

I tried relacing the if-else-statement with either one of these lines as a workaround, but in both cases either `TypeError: incompatible types for inplace operation` is thrown from `_quad2norm` (for `(Z|Z) < 1` with complex `Z`) or `Exception: quadratic form involving hermitian variable` is thrown from `_copy_dictexp_to_new_vars` (for `(Z|Z) < 1` with hermitian `Z`). My testing example is:
```
import picos
P = picos.Problem(solver="cvxopt")
Z = P.add_variable("Z", (2, 2), "complex")
P.add_constraint(Z|Z < 1)
P.solve()
```
Unfortunately I have no experience with the complex-number part of PICOS yet and I could look into this no earlier than next week.

**Comment by RPinto89** [comment] 2018-03-19 17:43
Your help is very much appreciated @Viech!

I will be waiting if you could come up with a solution for this!

Thank you

**Comment by mjstahlberg** [comment] 2018-03-28 14:27
At this point I'm really not sure how an inner product of complex matrices is supposed to be handled by PICOS.

Before I could even get to the point where `is_real` is called for a `QuadExp`, I noticed that the code in `add_constraint` that flags the problem as `_complex` states that quadratic expressions "should not contain complex coefficients", while really `Z|Z` for a complex 2×2 matrix `Z` is at some point converted to a quadratic expressions over real variables `Z_RE` and `Z_IM` with pure imaginary coefficients. Fixing the code so that a problem containing just the constraint `Z|Z < 1` is also flagged as `_complex` (a flag which would, by the way, not be reset if the constraint was deleted again) would then trigger a call to `to_real`, which gets us to @RPinto89's original problem of `AttributeError: 'QuadExp' object has no attribute 'is_real'`.

Again I tried to replace `if c.Exp1.is_real():` with `if True:` and `if False:`. In both cases I get a different kind of infinite loop now, and I could confirm (by adding `assert not real._complex`) that this is likely because none of the two options (`_copy_exp_to_new_vars(c.Exp1, cvars, complex=False)` and `_copy_exp_to_new_vars(c.Exp1, cvars, complex=True)`) would actually make the new constraint be real, even though the function does include code specific to `QuadExp`.

I then tried to dig deeper into the complex number part of PICOS to see if adding `is_real` to a quadratic expression and fixing `_copy_exp_to_new_vars` is even the crrect thing to do here, or if the real issue is that quadratic expressions can be complex at all, as the code comment in `add_constraint` suggested. Unfortunately I'm stuck at this point, and I'm afraid that without guidance through the design process it would take me a lot of reverse engineering time to understand how the code *should* function.

I'd be happy if @gsagnol would take another look at the issue, maybe the cause is more clear to him. My partial fix ot `add_constraint` is at Viech/picos@3c89eee5efeb5713f4493260d16f069c13479e59.

**Comment by RPinto89** [comment] 2018-03-28 14:54
Thank you @Viech for the time you spent around this. 
I'm hoping too that @gsagnol could take this another step further.

At this point I think it is important to remember that my original goal was to have as objective function the sum of several Frobenius norms **squared**:

![image](https://user-images.githubusercontent.com/14095892/38036190-13e15eec-329e-11e8-9fa3-174b11250235.png)

Now, you (@Viech) suggested that 

> Assuming that PICOS does not yet support complex numbers in quadratic objectives, such an epigraph reformulation with auxiliary variables should indeed be the correct way to work around it.

and so, I did just that I added those constraint to work around that limitation. Now, only abs() is working and not the actual inner product function "|". Note that the Frobenius norm **squared** of a complex function can be deducted as being the real part of the trace of that matrix:

![image](https://user-images.githubusercontent.com/14095892/38036701-313bc24c-329f-11e8-812b-7dbcd7ab4609.png)

@gsagnol do you have any idea on how can I formulate my objective function?

Thank you both!

**Comment by gsagnol** [comment] 2018-04-23 14:42
OK, sorry I did not have the time to look at it earlier.
So, if I get it well, the problem is with expressions of the form
``abs(z) <= t``, [which should now be fixed with #68]
and 
``abs(z)**2 <= t``

The problem is that ``abs(z)**2`` creates a complex valued quadratic expression. Complex quadratics are not supported, and we do not want to support them.

However, it is clear that ``abs(z)**2`` is real-valued. So a solution would be to reimplement the ``**2`` operation for this particular case, and ``abs(z)**2`` should create a handle to the real-valued quadratic expression ``z.real**2 + z.imag **2``. @Viech , can you take care of this?

**Comment by RPinto89** [comment] 2018-04-23 15:01
@gsagnol, my objective function is described in my last post. I need to sum all those elements.

![](https://user-images.githubusercontent.com/14095892/38036701-313bc24c-329f-11e8-812b-7dbcd7ab4609.png)

Each one is the squared Frobenius norm of the difference between two matrices. One matrix is a variable and the other a parameter. Basically I need the inner product of the difference of those matrices.
How should I implement that?

Thanks

**Comment by gsagnol** [comment] 2018-04-23 15:23
OK, sorry, in fact it should work already. @Viech, what I wrote above is already implemented,
so I think we can close this issue.

Quick summary:
``(z|z)<=t`` is not implemented, and probably never will
But...
``abs(z)**2<=t`` is equivalent, and works correctly.

@RPinto89, for your problem I guess that something like this should work:

``
prob.add_constraint( abs(S - S_i_ref)**2 <= t1)
prob.add_constraint( abs(S - S_Ai_ref)**2 <= t2)
prob.add_constraint( abs(l - l_i_ref)**2 <= t3)
prob.add_constraint( abs(l - l_Ai_ref)**2 <= t4)
prob.add_constraint( abs(v - v_i_ref)**2 <= t5)
prob.set_objective('min', (2*n_chi + 3) * t1 + t2 + (n_chi + 1) * t3 + t4 + 2 * t5)
``
And if I understand you first question correctly, I think you also need to add a constraint of the form
``
prob.add_constraint( ((v & S)//(S.H & l)) >> 0)
``

**Closed as completed by gsagnol** 2018-04-23 15:23 UTC

**Comment by RPinto89** [comment] 2018-04-23 15:39
I have implemented with abs(z)**2<=t and it seems to work.

Thank you both for your time.
