### ISSUE TITLE
SDPA solver is not working as expected

### ISSUE THREAD

**Issue by colombojrj** [gsagnol/picos#19] opened 2016-02-19 11:13 UTC
SDPA doesn't work to solve even simple SDP. It returns that the optimization problem is infeasible. However, CVXOPT solves it.

**Comment by peterwittek** [comment] 2016-02-19 11:15
Could you give an example? The problems I tested worked.

**Comment by colombojrj** [comment] 2016-02-19 11:25
Of course.

Be this simple example: fit a circle of radius 2.

import picos as pic
import numpy as np
prob = pic.Problem()
q = prob.add_variable('q', (1,1))
Q = ( (q & 0) // (0 & q) )
prob.add_constraint( Q >> np.zeros((2,2)) )
z = pic.new_param('z', np.array([[1],[1]]))
prob.add_constraint( ((1. & z.T) // (z & Q)) >> np.zeros((3,3)) )
prob.set_objective('min', q)
sol = prob.solve(solver='sdpa')

Error:

**\* Dualizing the problem...  ***
writing problem in /tmp/tmpWv8q81.dat-s...
SDPA solution status: unknown

---

Exception                                  Traceback (most recent call last)
<ipython-input-8-42079f327c7d>  in<module>() 8 prob.add_constraint( ((1. & z.T) // (z & Q)) >> 
np.zeros((3,3)) )9 prob.set_objective('min', q)---> 10sol = 
prob.solve(solver='sdpa')/usr/local/lib/python2.7/dist-packages/picos/problem.pyc 
in solve(self, **options) 4484 if self.options['verbose'] > 0:4485 raise 
Exception( -> 4486"\033[1;31m no Primals retrieved from the dual problem 
\033[0m") 4487 else:4488 xx = -xxException: no Primals retrieved from 
the dual problem 
####################################################################################### 

However, if I use CVXOPT,

###################################################

## **\* Dualizing the problem...  ***

##    cvxopt CONELP solver

```
  pcost       dcost       gap    pres   dres   k/t
```

  0:  0.0000e+00 -0.0000e+00  1e+01  2e+00  2e+00  1e+00
  1: -1.1662e+00 -9.5499e-01  2e+00  5e-01  4e-01  4e-01
  2: -1.7887e+00 -1.4611e+00  3e+00  4e-01  4e-01  5e-01
  3: -1.9586e+00 -1.9328e+00  2e-01  3e-02  3e-02  4e-02
  4: -2.0007e+00 -2.0011e+00  1e-02  2e-03  1e-03  3e-04
  5: -2.0000e+00 -2.0000e+00  1e-04  2e-05  2e-05  4e-06
  6: -2.0000e+00 -2.0000e+00  2e-06  3e-07  3e-07  7e-08
  7: -2.0000e+00 -2.0000e+00  7e-08  1e-08  9e-09  2e-09
Optimal solution found.
cvxopt status: optimal

Hope I gave enough information. I need to solve large optimization 
problems and CVXOPT is
quite slow. It would very useful if I may use SDPA or CSDP to solve my 
large SDP.

Thanks!

Em 19-02-2016 09:15, Peter Wittek escreveu:

> Could you give an example? The problems I tested worked.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/gsagnol/picos/issues/19#issuecomment-186175942.

## 

Atenciosamente,

José Roberto.

**Comment by peterwittek** [comment] 2016-02-19 11:46
I confirm, the temporary dat-s file written is utter rubbish. This is clearly a bug. I will look into it as soon as I can.

**Comment by peterwittek** [comment] 2016-02-22 11:10
I found the source of the problem. SDPA solves the optimization without issues. The primal solution is returned and the value is correct. The issue is that the dual solution is not parsed, and PICOS complains about it.

**Comment by peterwittek** [comment] 2016-02-22 11:18
PICOS wants to dualize this problem, read the solution, then switch back to the primal. Until the dual parser for SDPA is written, the following workaround will solve the problem:

```
sol = prob.solve(solver='sdpa', solve_via_dual=False)
```

SDPA returns a wide array of statuses. I just opened a pull request to parse the status for this problem correctly.

**Comment by gsagnol** [comment] 2016-02-22 11:47
Thanks Peter ! I just merged.

**Comment by gsagnol** [comment] 2016-06-30 09:48
The SDPA dual parser works correctly now, so we can close this issue

**Closed as completed by gsagnol** 2016-06-30 09:48 UTC
